{{- include "cartforge.validateSecrets" . }}
{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cartforge.secretName" . }}
  labels:
    {{- include "cartforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.postgresPasswordKey }}: {{ .Values.secrets.postgresPassword | quote }}
  {{ .Values.secrets.jwtSecretKey }}: {{ .Values.secrets.jwtSecret | quote }}
{{- end }}
