CREATE TABLE checkout_idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    order_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_checkout_idempotency_keys PRIMARY KEY (id),
    CONSTRAINT uq_checkout_idempotency_user_key UNIQUE (user_id, idempotency_key),
    CONSTRAINT uq_checkout_idempotency_order UNIQUE (order_id),
    CONSTRAINT fk_checkout_idempotency_users FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_checkout_idempotency_orders FOREIGN KEY (order_id)
        REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT ck_checkout_idempotency_key_not_blank CHECK (length(btrim(idempotency_key)) > 0),
    CONSTRAINT ck_checkout_idempotency_fingerprint CHECK (request_fingerprint ~ '^[0-9a-f]{64}$')
);

CREATE INDEX ix_checkout_idempotency_user_id ON checkout_idempotency_keys (user_id);
