CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'ADMIN')),
    CONSTRAINT ck_users_email_not_blank CHECK (length(btrim(email)) > 0),
    CONSTRAINT ck_users_password_hash_not_blank CHECK (length(btrim(password_hash)) > 0),
    CONSTRAINT ck_users_first_name_not_blank CHECK (length(btrim(first_name)) > 0),
    CONSTRAINT ck_users_last_name_not_blank CHECK (length(btrim(last_name)) > 0)
);

CREATE UNIQUE INDEX uq_users_email_lower ON users (LOWER(email));
