CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sku VARCHAR(64) NOT NULL,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL,
    description VARCHAR(4000),
    price NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    category_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT uq_products_slug UNIQUE (slug),
    CONSTRAINT fk_products_categories FOREIGN KEY (category_id)
        REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT ck_products_sku_not_blank CHECK (length(btrim(sku)) > 0),
    CONSTRAINT ck_products_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_products_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT ck_products_currency_format CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_products_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_products_stock_quantity_non_negative CHECK (stock_quantity >= 0)
);

CREATE INDEX ix_products_category_id ON products (category_id);
CREATE INDEX ix_products_active ON products (active);
CREATE INDEX ix_products_price ON products (price);
CREATE INDEX ix_products_name ON products (name);
