CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_number VARCHAR(32) NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',
    shipping_address VARCHAR(1000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uq_orders_order_number UNIQUE (order_number),
    CONSTRAINT fk_orders_users FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_orders_status CHECK (
        status IN ('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_orders_order_number_not_blank CHECK (length(btrim(order_number)) > 0),
    CONSTRAINT ck_orders_shipping_address_not_blank CHECK (length(btrim(shipping_address)) > 0),
    CONSTRAINT ck_orders_currency_format CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_orders_total_amount_non_negative CHECK (total_amount >= 0)
);

CREATE INDEX ix_orders_user_id ON orders (user_id);
CREATE INDEX ix_orders_status ON orders (status);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(200) NOT NULL,
    sku VARCHAR(64) NOT NULL,
    unit_price NUMERIC(19, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    line_total NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_orders FOREIGN KEY (order_id)
        REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_products FOREIGN KEY (product_id)
        REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT ck_order_items_product_name_not_blank CHECK (length(btrim(product_name)) > 0),
    CONSTRAINT ck_order_items_sku_not_blank CHECK (length(btrim(sku)) > 0),
    CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_order_items_unit_price_non_negative CHECK (unit_price >= 0),
    -- The snapshot must stay internally consistent: a line total can never
    -- drift from the unit price it was captured with.
    CONSTRAINT ck_order_items_line_total CHECK (line_total = unit_price * quantity)
);

CREATE INDEX ix_order_items_order_id ON order_items (order_id);
-- product_id is a RESTRICT parent check and the "has this product ever been
-- ordered?" lookup behind soft deactivation; PostgreSQL does not index it.
CREATE INDEX ix_order_items_product_id ON order_items (product_id);
